; Created by ConvertChessPieces.py
 DEF PIECE_VECTOR_LO
 .byte <WHITE_BLANK_on_WHITE_SQUARE_0
 .byte <WHITE_BLANK_on_WHITE_SQUARE_1
 .byte <WHITE_BLANK_on_WHITE_SQUARE_2
 .byte <WHITE_BLANK_on_WHITE_SQUARE_3
 .byte <WHITE_PAWN_on_WHITE_SQUARE_0
 .byte <WHITE_PAWN_on_WHITE_SQUARE_1
 .byte <WHITE_PAWN_on_WHITE_SQUARE_2
 .byte <WHITE_PAWN_on_WHITE_SQUARE_3
 .byte <WHITE_KNIGHT_on_WHITE_SQUARE_0
 .byte <WHITE_KNIGHT_on_WHITE_SQUARE_1
 .byte <WHITE_KNIGHT_on_WHITE_SQUARE_2
 .byte <WHITE_KNIGHT_on_WHITE_SQUARE_3
 .byte <WHITE_BISHOP_on_WHITE_SQUARE_0
 .byte <WHITE_BISHOP_on_WHITE_SQUARE_1
 .byte <WHITE_BISHOP_on_WHITE_SQUARE_2
 .byte <WHITE_BISHOP_on_WHITE_SQUARE_3
 .byte <WHITE_ROOK_on_WHITE_SQUARE_0
 .byte <WHITE_ROOK_on_WHITE_SQUARE_1
 .byte <WHITE_ROOK_on_WHITE_SQUARE_2
 .byte <WHITE_ROOK_on_WHITE_SQUARE_3
 .byte <WHITE_QUEEN_on_WHITE_SQUARE_0
 .byte <WHITE_QUEEN_on_WHITE_SQUARE_1
 .byte <WHITE_QUEEN_on_WHITE_SQUARE_2
 .byte <WHITE_QUEEN_on_WHITE_SQUARE_3
 .byte <WHITE_KING_on_WHITE_SQUARE_0
 .byte <WHITE_KING_on_WHITE_SQUARE_1
 .byte <WHITE_KING_on_WHITE_SQUARE_2
 .byte <WHITE_KING_on_WHITE_SQUARE_3
 .byte <WHITE_BLANK_on_BLACK_SQUARE_0
 .byte <WHITE_BLANK_on_BLACK_SQUARE_1
 .byte <WHITE_BLANK_on_BLACK_SQUARE_2
 .byte <WHITE_BLANK_on_BLACK_SQUARE_3
 .byte <WHITE_PAWN_on_BLACK_SQUARE_0
 .byte <WHITE_PAWN_on_BLACK_SQUARE_1
 .byte <WHITE_PAWN_on_BLACK_SQUARE_2
 .byte <WHITE_PAWN_on_BLACK_SQUARE_3
 .byte <WHITE_KNIGHT_on_BLACK_SQUARE_0
 .byte <WHITE_KNIGHT_on_BLACK_SQUARE_1
 .byte <WHITE_KNIGHT_on_BLACK_SQUARE_2
 .byte <WHITE_KNIGHT_on_BLACK_SQUARE_3
 .byte <WHITE_BISHOP_on_BLACK_SQUARE_0
 .byte <WHITE_BISHOP_on_BLACK_SQUARE_1
 .byte <WHITE_BISHOP_on_BLACK_SQUARE_2
 .byte <WHITE_BISHOP_on_BLACK_SQUARE_3
 .byte <WHITE_ROOK_on_BLACK_SQUARE_0
 .byte <WHITE_ROOK_on_BLACK_SQUARE_1
 .byte <WHITE_ROOK_on_BLACK_SQUARE_2
 .byte <WHITE_ROOK_on_BLACK_SQUARE_3
 .byte <WHITE_QUEEN_on_BLACK_SQUARE_0
 .byte <WHITE_QUEEN_on_BLACK_SQUARE_1
 .byte <WHITE_QUEEN_on_BLACK_SQUARE_2
 .byte <WHITE_QUEEN_on_BLACK_SQUARE_3
 .byte <WHITE_KING_on_BLACK_SQUARE_0
 .byte <WHITE_KING_on_BLACK_SQUARE_1
 .byte <WHITE_KING_on_BLACK_SQUARE_2
 .byte <WHITE_KING_on_BLACK_SQUARE_3
 .byte <BLACK_BLANK_on_WHITE_SQUARE_0
 .byte <BLACK_BLANK_on_WHITE_SQUARE_1
 .byte <BLACK_BLANK_on_WHITE_SQUARE_2
 .byte <BLACK_BLANK_on_WHITE_SQUARE_3
 .byte <BLACK_PAWN_on_WHITE_SQUARE_0
 .byte <BLACK_PAWN_on_WHITE_SQUARE_1
 .byte <BLACK_PAWN_on_WHITE_SQUARE_2
 .byte <BLACK_PAWN_on_WHITE_SQUARE_3
 .byte <BLACK_KNIGHT_on_WHITE_SQUARE_0
 .byte <BLACK_KNIGHT_on_WHITE_SQUARE_1
 .byte <BLACK_KNIGHT_on_WHITE_SQUARE_2
 .byte <BLACK_KNIGHT_on_WHITE_SQUARE_3
 .byte <BLACK_BISHOP_on_WHITE_SQUARE_0
 .byte <BLACK_BISHOP_on_WHITE_SQUARE_1
 .byte <BLACK_BISHOP_on_WHITE_SQUARE_2
 .byte <BLACK_BISHOP_on_WHITE_SQUARE_3
 .byte <BLACK_ROOK_on_WHITE_SQUARE_0
 .byte <BLACK_ROOK_on_WHITE_SQUARE_1
 .byte <BLACK_ROOK_on_WHITE_SQUARE_2
 .byte <BLACK_ROOK_on_WHITE_SQUARE_3
 .byte <BLACK_QUEEN_on_WHITE_SQUARE_0
 .byte <BLACK_QUEEN_on_WHITE_SQUARE_1
 .byte <BLACK_QUEEN_on_WHITE_SQUARE_2
 .byte <BLACK_QUEEN_on_WHITE_SQUARE_3
 .byte <BLACK_KING_on_WHITE_SQUARE_0
 .byte <BLACK_KING_on_WHITE_SQUARE_1
 .byte <BLACK_KING_on_WHITE_SQUARE_2
 .byte <BLACK_KING_on_WHITE_SQUARE_3
 .byte <BLACK_BLANK_on_BLACK_SQUARE_0
 .byte <BLACK_BLANK_on_BLACK_SQUARE_1
 .byte <BLACK_BLANK_on_BLACK_SQUARE_2
 .byte <BLACK_BLANK_on_BLACK_SQUARE_3
 .byte <BLACK_PAWN_on_BLACK_SQUARE_0
 .byte <BLACK_PAWN_on_BLACK_SQUARE_1
 .byte <BLACK_PAWN_on_BLACK_SQUARE_2
 .byte <BLACK_PAWN_on_BLACK_SQUARE_3
 .byte <BLACK_KNIGHT_on_BLACK_SQUARE_0
 .byte <BLACK_KNIGHT_on_BLACK_SQUARE_1
 .byte <BLACK_KNIGHT_on_BLACK_SQUARE_2
 .byte <BLACK_KNIGHT_on_BLACK_SQUARE_3
 .byte <BLACK_BISHOP_on_BLACK_SQUARE_0
 .byte <BLACK_BISHOP_on_BLACK_SQUARE_1
 .byte <BLACK_BISHOP_on_BLACK_SQUARE_2
 .byte <BLACK_BISHOP_on_BLACK_SQUARE_3
 .byte <BLACK_ROOK_on_BLACK_SQUARE_0
 .byte <BLACK_ROOK_on_BLACK_SQUARE_1
 .byte <BLACK_ROOK_on_BLACK_SQUARE_2
 .byte <BLACK_ROOK_on_BLACK_SQUARE_3
 .byte <BLACK_QUEEN_on_BLACK_SQUARE_0
 .byte <BLACK_QUEEN_on_BLACK_SQUARE_1
 .byte <BLACK_QUEEN_on_BLACK_SQUARE_2
 .byte <BLACK_QUEEN_on_BLACK_SQUARE_3
 .byte <BLACK_KING_on_BLACK_SQUARE_0
 .byte <BLACK_KING_on_BLACK_SQUARE_1
 .byte <BLACK_KING_on_BLACK_SQUARE_2
 .byte <BLACK_KING_on_BLACK_SQUARE_3
 DEF PIECE_VECTOR_HI
 .byte >WHITE_BLANK_on_WHITE_SQUARE_0
 .byte >WHITE_BLANK_on_WHITE_SQUARE_1
 .byte >WHITE_BLANK_on_WHITE_SQUARE_2
 .byte >WHITE_BLANK_on_WHITE_SQUARE_3
 .byte >WHITE_PAWN_on_WHITE_SQUARE_0
 .byte >WHITE_PAWN_on_WHITE_SQUARE_1
 .byte >WHITE_PAWN_on_WHITE_SQUARE_2
 .byte >WHITE_PAWN_on_WHITE_SQUARE_3
 .byte >WHITE_KNIGHT_on_WHITE_SQUARE_0
 .byte >WHITE_KNIGHT_on_WHITE_SQUARE_1
 .byte >WHITE_KNIGHT_on_WHITE_SQUARE_2
 .byte >WHITE_KNIGHT_on_WHITE_SQUARE_3
 .byte >WHITE_BISHOP_on_WHITE_SQUARE_0
 .byte >WHITE_BISHOP_on_WHITE_SQUARE_1
 .byte >WHITE_BISHOP_on_WHITE_SQUARE_2
 .byte >WHITE_BISHOP_on_WHITE_SQUARE_3
 .byte >WHITE_ROOK_on_WHITE_SQUARE_0
 .byte >WHITE_ROOK_on_WHITE_SQUARE_1
 .byte >WHITE_ROOK_on_WHITE_SQUARE_2
 .byte >WHITE_ROOK_on_WHITE_SQUARE_3
 .byte >WHITE_QUEEN_on_WHITE_SQUARE_0
 .byte >WHITE_QUEEN_on_WHITE_SQUARE_1
 .byte >WHITE_QUEEN_on_WHITE_SQUARE_2
 .byte >WHITE_QUEEN_on_WHITE_SQUARE_3
 .byte >WHITE_KING_on_WHITE_SQUARE_0
 .byte >WHITE_KING_on_WHITE_SQUARE_1
 .byte >WHITE_KING_on_WHITE_SQUARE_2
 .byte >WHITE_KING_on_WHITE_SQUARE_3
 .byte >WHITE_BLANK_on_BLACK_SQUARE_0
 .byte >WHITE_BLANK_on_BLACK_SQUARE_1
 .byte >WHITE_BLANK_on_BLACK_SQUARE_2
 .byte >WHITE_BLANK_on_BLACK_SQUARE_3
 .byte >WHITE_PAWN_on_BLACK_SQUARE_0
 .byte >WHITE_PAWN_on_BLACK_SQUARE_1
 .byte >WHITE_PAWN_on_BLACK_SQUARE_2
 .byte >WHITE_PAWN_on_BLACK_SQUARE_3
 .byte >WHITE_KNIGHT_on_BLACK_SQUARE_0
 .byte >WHITE_KNIGHT_on_BLACK_SQUARE_1
 .byte >WHITE_KNIGHT_on_BLACK_SQUARE_2
 .byte >WHITE_KNIGHT_on_BLACK_SQUARE_3
 .byte >WHITE_BISHOP_on_BLACK_SQUARE_0
 .byte >WHITE_BISHOP_on_BLACK_SQUARE_1
 .byte >WHITE_BISHOP_on_BLACK_SQUARE_2
 .byte >WHITE_BISHOP_on_BLACK_SQUARE_3
 .byte >WHITE_ROOK_on_BLACK_SQUARE_0
 .byte >WHITE_ROOK_on_BLACK_SQUARE_1
 .byte >WHITE_ROOK_on_BLACK_SQUARE_2
 .byte >WHITE_ROOK_on_BLACK_SQUARE_3
 .byte >WHITE_QUEEN_on_BLACK_SQUARE_0
 .byte >WHITE_QUEEN_on_BLACK_SQUARE_1
 .byte >WHITE_QUEEN_on_BLACK_SQUARE_2
 .byte >WHITE_QUEEN_on_BLACK_SQUARE_3
 .byte >WHITE_KING_on_BLACK_SQUARE_0
 .byte >WHITE_KING_on_BLACK_SQUARE_1
 .byte >WHITE_KING_on_BLACK_SQUARE_2
 .byte >WHITE_KING_on_BLACK_SQUARE_3
 .byte >BLACK_BLANK_on_WHITE_SQUARE_0
 .byte >BLACK_BLANK_on_WHITE_SQUARE_1
 .byte >BLACK_BLANK_on_WHITE_SQUARE_2
 .byte >BLACK_BLANK_on_WHITE_SQUARE_3
 .byte >BLACK_PAWN_on_WHITE_SQUARE_0
 .byte >BLACK_PAWN_on_WHITE_SQUARE_1
 .byte >BLACK_PAWN_on_WHITE_SQUARE_2
 .byte >BLACK_PAWN_on_WHITE_SQUARE_3
 .byte >BLACK_KNIGHT_on_WHITE_SQUARE_0
 .byte >BLACK_KNIGHT_on_WHITE_SQUARE_1
 .byte >BLACK_KNIGHT_on_WHITE_SQUARE_2
 .byte >BLACK_KNIGHT_on_WHITE_SQUARE_3
 .byte >BLACK_BISHOP_on_WHITE_SQUARE_0
 .byte >BLACK_BISHOP_on_WHITE_SQUARE_1
 .byte >BLACK_BISHOP_on_WHITE_SQUARE_2
 .byte >BLACK_BISHOP_on_WHITE_SQUARE_3
 .byte >BLACK_ROOK_on_WHITE_SQUARE_0
 .byte >BLACK_ROOK_on_WHITE_SQUARE_1
 .byte >BLACK_ROOK_on_WHITE_SQUARE_2
 .byte >BLACK_ROOK_on_WHITE_SQUARE_3
 .byte >BLACK_QUEEN_on_WHITE_SQUARE_0
 .byte >BLACK_QUEEN_on_WHITE_SQUARE_1
 .byte >BLACK_QUEEN_on_WHITE_SQUARE_2
 .byte >BLACK_QUEEN_on_WHITE_SQUARE_3
 .byte >BLACK_KING_on_WHITE_SQUARE_0
 .byte >BLACK_KING_on_WHITE_SQUARE_1
 .byte >BLACK_KING_on_WHITE_SQUARE_2
 .byte >BLACK_KING_on_WHITE_SQUARE_3
 .byte >BLACK_BLANK_on_BLACK_SQUARE_0
 .byte >BLACK_BLANK_on_BLACK_SQUARE_1
 .byte >BLACK_BLANK_on_BLACK_SQUARE_2
 .byte >BLACK_BLANK_on_BLACK_SQUARE_3
 .byte >BLACK_PAWN_on_BLACK_SQUARE_0
 .byte >BLACK_PAWN_on_BLACK_SQUARE_1
 .byte >BLACK_PAWN_on_BLACK_SQUARE_2
 .byte >BLACK_PAWN_on_BLACK_SQUARE_3
 .byte >BLACK_KNIGHT_on_BLACK_SQUARE_0
 .byte >BLACK_KNIGHT_on_BLACK_SQUARE_1
 .byte >BLACK_KNIGHT_on_BLACK_SQUARE_2
 .byte >BLACK_KNIGHT_on_BLACK_SQUARE_3
 .byte >BLACK_BISHOP_on_BLACK_SQUARE_0
 .byte >BLACK_BISHOP_on_BLACK_SQUARE_1
 .byte >BLACK_BISHOP_on_BLACK_SQUARE_2
 .byte >BLACK_BISHOP_on_BLACK_SQUARE_3
 .byte >BLACK_ROOK_on_BLACK_SQUARE_0
 .byte >BLACK_ROOK_on_BLACK_SQUARE_1
 .byte >BLACK_ROOK_on_BLACK_SQUARE_2
 .byte >BLACK_ROOK_on_BLACK_SQUARE_3
 .byte >BLACK_QUEEN_on_BLACK_SQUARE_0
 .byte >BLACK_QUEEN_on_BLACK_SQUARE_1
 .byte >BLACK_QUEEN_on_BLACK_SQUARE_2
 .byte >BLACK_QUEEN_on_BLACK_SQUARE_3
 .byte >BLACK_KING_on_BLACK_SQUARE_0
 .byte >BLACK_KING_on_BLACK_SQUARE_1
 .byte >BLACK_KING_on_BLACK_SQUARE_2
 .byte >BLACK_KING_on_BLACK_SQUARE_3
 DEF PIECE_VECTOR_BANK
 .byte BANK_WHITE_BLANK_on_WHITE_SQUARE_0
 .byte BANK_WHITE_BLANK_on_WHITE_SQUARE_1
 .byte BANK_WHITE_BLANK_on_WHITE_SQUARE_2
 .byte BANK_WHITE_BLANK_on_WHITE_SQUARE_3
 .byte BANK_WHITE_PAWN_on_WHITE_SQUARE_0
 .byte BANK_WHITE_PAWN_on_WHITE_SQUARE_1
 .byte BANK_WHITE_PAWN_on_WHITE_SQUARE_2
 .byte BANK_WHITE_PAWN_on_WHITE_SQUARE_3
 .byte BANK_WHITE_KNIGHT_on_WHITE_SQUARE_0
 .byte BANK_WHITE_KNIGHT_on_WHITE_SQUARE_1
 .byte BANK_WHITE_KNIGHT_on_WHITE_SQUARE_2
 .byte BANK_WHITE_KNIGHT_on_WHITE_SQUARE_3
 .byte BANK_WHITE_BISHOP_on_WHITE_SQUARE_0
 .byte BANK_WHITE_BISHOP_on_WHITE_SQUARE_1
 .byte BANK_WHITE_BISHOP_on_WHITE_SQUARE_2
 .byte BANK_WHITE_BISHOP_on_WHITE_SQUARE_3
 .byte BANK_WHITE_ROOK_on_WHITE_SQUARE_0
 .byte BANK_WHITE_ROOK_on_WHITE_SQUARE_1
 .byte BANK_WHITE_ROOK_on_WHITE_SQUARE_2
 .byte BANK_WHITE_ROOK_on_WHITE_SQUARE_3
 .byte BANK_WHITE_QUEEN_on_WHITE_SQUARE_0
 .byte BANK_WHITE_QUEEN_on_WHITE_SQUARE_1
 .byte BANK_WHITE_QUEEN_on_WHITE_SQUARE_2
 .byte BANK_WHITE_QUEEN_on_WHITE_SQUARE_3
 .byte BANK_WHITE_KING_on_WHITE_SQUARE_0
 .byte BANK_WHITE_KING_on_WHITE_SQUARE_1
 .byte BANK_WHITE_KING_on_WHITE_SQUARE_2
 .byte BANK_WHITE_KING_on_WHITE_SQUARE_3
 .byte BANK_WHITE_BLANK_on_BLACK_SQUARE_0
 .byte BANK_WHITE_BLANK_on_BLACK_SQUARE_1
 .byte BANK_WHITE_BLANK_on_BLACK_SQUARE_2
 .byte BANK_WHITE_BLANK_on_BLACK_SQUARE_3
 .byte BANK_WHITE_PAWN_on_BLACK_SQUARE_0
 .byte BANK_WHITE_PAWN_on_BLACK_SQUARE_1
 .byte BANK_WHITE_PAWN_on_BLACK_SQUARE_2
 .byte BANK_WHITE_PAWN_on_BLACK_SQUARE_3
 .byte BANK_WHITE_KNIGHT_on_BLACK_SQUARE_0
 .byte BANK_WHITE_KNIGHT_on_BLACK_SQUARE_1
 .byte BANK_WHITE_KNIGHT_on_BLACK_SQUARE_2
 .byte BANK_WHITE_KNIGHT_on_BLACK_SQUARE_3
 .byte BANK_WHITE_BISHOP_on_BLACK_SQUARE_0
 .byte BANK_WHITE_BISHOP_on_BLACK_SQUARE_1
 .byte BANK_WHITE_BISHOP_on_BLACK_SQUARE_2
 .byte BANK_WHITE_BISHOP_on_BLACK_SQUARE_3
 .byte BANK_WHITE_ROOK_on_BLACK_SQUARE_0
 .byte BANK_WHITE_ROOK_on_BLACK_SQUARE_1
 .byte BANK_WHITE_ROOK_on_BLACK_SQUARE_2
 .byte BANK_WHITE_ROOK_on_BLACK_SQUARE_3
 .byte BANK_WHITE_QUEEN_on_BLACK_SQUARE_0
 .byte BANK_WHITE_QUEEN_on_BLACK_SQUARE_1
 .byte BANK_WHITE_QUEEN_on_BLACK_SQUARE_2
 .byte BANK_WHITE_QUEEN_on_BLACK_SQUARE_3
 .byte BANK_WHITE_KING_on_BLACK_SQUARE_0
 .byte BANK_WHITE_KING_on_BLACK_SQUARE_1
 .byte BANK_WHITE_KING_on_BLACK_SQUARE_2
 .byte BANK_WHITE_KING_on_BLACK_SQUARE_3
 .byte BANK_BLACK_BLANK_on_WHITE_SQUARE_0
 .byte BANK_BLACK_BLANK_on_WHITE_SQUARE_1
 .byte BANK_BLACK_BLANK_on_WHITE_SQUARE_2
 .byte BANK_BLACK_BLANK_on_WHITE_SQUARE_3
 .byte BANK_BLACK_PAWN_on_WHITE_SQUARE_0
 .byte BANK_BLACK_PAWN_on_WHITE_SQUARE_1
 .byte BANK_BLACK_PAWN_on_WHITE_SQUARE_2
 .byte BANK_BLACK_PAWN_on_WHITE_SQUARE_3
 .byte BANK_BLACK_KNIGHT_on_WHITE_SQUARE_0
 .byte BANK_BLACK_KNIGHT_on_WHITE_SQUARE_1
 .byte BANK_BLACK_KNIGHT_on_WHITE_SQUARE_2
 .byte BANK_BLACK_KNIGHT_on_WHITE_SQUARE_3
 .byte BANK_BLACK_BISHOP_on_WHITE_SQUARE_0
 .byte BANK_BLACK_BISHOP_on_WHITE_SQUARE_1
 .byte BANK_BLACK_BISHOP_on_WHITE_SQUARE_2
 .byte BANK_BLACK_BISHOP_on_WHITE_SQUARE_3
 .byte BANK_BLACK_ROOK_on_WHITE_SQUARE_0
 .byte BANK_BLACK_ROOK_on_WHITE_SQUARE_1
 .byte BANK_BLACK_ROOK_on_WHITE_SQUARE_2
 .byte BANK_BLACK_ROOK_on_WHITE_SQUARE_3
 .byte BANK_BLACK_QUEEN_on_WHITE_SQUARE_0
 .byte BANK_BLACK_QUEEN_on_WHITE_SQUARE_1
 .byte BANK_BLACK_QUEEN_on_WHITE_SQUARE_2
 .byte BANK_BLACK_QUEEN_on_WHITE_SQUARE_3
 .byte BANK_BLACK_KING_on_WHITE_SQUARE_0
 .byte BANK_BLACK_KING_on_WHITE_SQUARE_1
 .byte BANK_BLACK_KING_on_WHITE_SQUARE_2
 .byte BANK_BLACK_KING_on_WHITE_SQUARE_3
 .byte BANK_BLACK_BLANK_on_BLACK_SQUARE_0
 .byte BANK_BLACK_BLANK_on_BLACK_SQUARE_1
 .byte BANK_BLACK_BLANK_on_BLACK_SQUARE_2
 .byte BANK_BLACK_BLANK_on_BLACK_SQUARE_3
 .byte BANK_BLACK_PAWN_on_BLACK_SQUARE_0
 .byte BANK_BLACK_PAWN_on_BLACK_SQUARE_1
 .byte BANK_BLACK_PAWN_on_BLACK_SQUARE_2
 .byte BANK_BLACK_PAWN_on_BLACK_SQUARE_3
 .byte BANK_BLACK_KNIGHT_on_BLACK_SQUARE_0
 .byte BANK_BLACK_KNIGHT_on_BLACK_SQUARE_1
 .byte BANK_BLACK_KNIGHT_on_BLACK_SQUARE_2
 .byte BANK_BLACK_KNIGHT_on_BLACK_SQUARE_3
 .byte BANK_BLACK_BISHOP_on_BLACK_SQUARE_0
 .byte BANK_BLACK_BISHOP_on_BLACK_SQUARE_1
 .byte BANK_BLACK_BISHOP_on_BLACK_SQUARE_2
 .byte BANK_BLACK_BISHOP_on_BLACK_SQUARE_3
 .byte BANK_BLACK_ROOK_on_BLACK_SQUARE_0
 .byte BANK_BLACK_ROOK_on_BLACK_SQUARE_1
 .byte BANK_BLACK_ROOK_on_BLACK_SQUARE_2
 .byte BANK_BLACK_ROOK_on_BLACK_SQUARE_3
 .byte BANK_BLACK_QUEEN_on_BLACK_SQUARE_0
 .byte BANK_BLACK_QUEEN_on_BLACK_SQUARE_1
 .byte BANK_BLACK_QUEEN_on_BLACK_SQUARE_2
 .byte BANK_BLACK_QUEEN_on_BLACK_SQUARE_3
 .byte BANK_BLACK_KING_on_BLACK_SQUARE_0
 .byte BANK_BLACK_KING_on_BLACK_SQUARE_1
 .byte BANK_BLACK_KING_on_BLACK_SQUARE_2
 .byte BANK_BLACK_KING_on_BLACK_SQUARE_3

; piece index equates...
INDEX_WHITE_BLANK_on_WHITE_SQUARE_0=0
INDEX_WHITE_BLANK_on_WHITE_SQUARE_1=1
INDEX_WHITE_BLANK_on_WHITE_SQUARE_2=2
INDEX_WHITE_BLANK_on_WHITE_SQUARE_3=3
INDEX_WHITE_PAWN_on_WHITE_SQUARE_0=4
INDEX_WHITE_PAWN_on_WHITE_SQUARE_1=5
INDEX_WHITE_PAWN_on_WHITE_SQUARE_2=6
INDEX_WHITE_PAWN_on_WHITE_SQUARE_3=7
INDEX_WHITE_KNIGHT_on_WHITE_SQUARE_0=8
INDEX_WHITE_KNIGHT_on_WHITE_SQUARE_1=9
INDEX_WHITE_KNIGHT_on_WHITE_SQUARE_2=10
INDEX_WHITE_KNIGHT_on_WHITE_SQUARE_3=11
INDEX_WHITE_BISHOP_on_WHITE_SQUARE_0=12
INDEX_WHITE_BISHOP_on_WHITE_SQUARE_1=13
INDEX_WHITE_BISHOP_on_WHITE_SQUARE_2=14
INDEX_WHITE_BISHOP_on_WHITE_SQUARE_3=15
INDEX_WHITE_ROOK_on_WHITE_SQUARE_0=16
INDEX_WHITE_ROOK_on_WHITE_SQUARE_1=17
INDEX_WHITE_ROOK_on_WHITE_SQUARE_2=18
INDEX_WHITE_ROOK_on_WHITE_SQUARE_3=19
INDEX_WHITE_QUEEN_on_WHITE_SQUARE_0=20
INDEX_WHITE_QUEEN_on_WHITE_SQUARE_1=21
INDEX_WHITE_QUEEN_on_WHITE_SQUARE_2=22
INDEX_WHITE_QUEEN_on_WHITE_SQUARE_3=23
INDEX_WHITE_KING_on_WHITE_SQUARE_0=24
INDEX_WHITE_KING_on_WHITE_SQUARE_1=25
INDEX_WHITE_KING_on_WHITE_SQUARE_2=26
INDEX_WHITE_KING_on_WHITE_SQUARE_3=27
INDEX_WHITE_BLANK_on_BLACK_SQUARE_0=28
INDEX_WHITE_BLANK_on_BLACK_SQUARE_1=29
INDEX_WHITE_BLANK_on_BLACK_SQUARE_2=30
INDEX_WHITE_BLANK_on_BLACK_SQUARE_3=31
INDEX_WHITE_PAWN_on_BLACK_SQUARE_0=32
INDEX_WHITE_PAWN_on_BLACK_SQUARE_1=33
INDEX_WHITE_PAWN_on_BLACK_SQUARE_2=34
INDEX_WHITE_PAWN_on_BLACK_SQUARE_3=35
INDEX_WHITE_KNIGHT_on_BLACK_SQUARE_0=36
INDEX_WHITE_KNIGHT_on_BLACK_SQUARE_1=37
INDEX_WHITE_KNIGHT_on_BLACK_SQUARE_2=38
INDEX_WHITE_KNIGHT_on_BLACK_SQUARE_3=39
INDEX_WHITE_BISHOP_on_BLACK_SQUARE_0=40
INDEX_WHITE_BISHOP_on_BLACK_SQUARE_1=41
INDEX_WHITE_BISHOP_on_BLACK_SQUARE_2=42
INDEX_WHITE_BISHOP_on_BLACK_SQUARE_3=43
INDEX_WHITE_ROOK_on_BLACK_SQUARE_0=44
INDEX_WHITE_ROOK_on_BLACK_SQUARE_1=45
INDEX_WHITE_ROOK_on_BLACK_SQUARE_2=46
INDEX_WHITE_ROOK_on_BLACK_SQUARE_3=47
INDEX_WHITE_QUEEN_on_BLACK_SQUARE_0=48
INDEX_WHITE_QUEEN_on_BLACK_SQUARE_1=49
INDEX_WHITE_QUEEN_on_BLACK_SQUARE_2=50
INDEX_WHITE_QUEEN_on_BLACK_SQUARE_3=51
INDEX_WHITE_KING_on_BLACK_SQUARE_0=52
INDEX_WHITE_KING_on_BLACK_SQUARE_1=53
INDEX_WHITE_KING_on_BLACK_SQUARE_2=54
INDEX_WHITE_KING_on_BLACK_SQUARE_3=55
INDEX_BLACK_BLANK_on_WHITE_SQUARE_0=56
INDEX_BLACK_BLANK_on_WHITE_SQUARE_1=57
INDEX_BLACK_BLANK_on_WHITE_SQUARE_2=58
INDEX_BLACK_BLANK_on_WHITE_SQUARE_3=59
INDEX_BLACK_PAWN_on_WHITE_SQUARE_0=60
INDEX_BLACK_PAWN_on_WHITE_SQUARE_1=61
INDEX_BLACK_PAWN_on_WHITE_SQUARE_2=62
INDEX_BLACK_PAWN_on_WHITE_SQUARE_3=63
INDEX_BLACK_KNIGHT_on_WHITE_SQUARE_0=64
INDEX_BLACK_KNIGHT_on_WHITE_SQUARE_1=65
INDEX_BLACK_KNIGHT_on_WHITE_SQUARE_2=66
INDEX_BLACK_KNIGHT_on_WHITE_SQUARE_3=67
INDEX_BLACK_BISHOP_on_WHITE_SQUARE_0=68
INDEX_BLACK_BISHOP_on_WHITE_SQUARE_1=69
INDEX_BLACK_BISHOP_on_WHITE_SQUARE_2=70
INDEX_BLACK_BISHOP_on_WHITE_SQUARE_3=71
INDEX_BLACK_ROOK_on_WHITE_SQUARE_0=72
INDEX_BLACK_ROOK_on_WHITE_SQUARE_1=73
INDEX_BLACK_ROOK_on_WHITE_SQUARE_2=74
INDEX_BLACK_ROOK_on_WHITE_SQUARE_3=75
INDEX_BLACK_QUEEN_on_WHITE_SQUARE_0=76
INDEX_BLACK_QUEEN_on_WHITE_SQUARE_1=77
INDEX_BLACK_QUEEN_on_WHITE_SQUARE_2=78
INDEX_BLACK_QUEEN_on_WHITE_SQUARE_3=79
INDEX_BLACK_KING_on_WHITE_SQUARE_0=80
INDEX_BLACK_KING_on_WHITE_SQUARE_1=81
INDEX_BLACK_KING_on_WHITE_SQUARE_2=82
INDEX_BLACK_KING_on_WHITE_SQUARE_3=83
INDEX_BLACK_BLANK_on_BLACK_SQUARE_0=84
INDEX_BLACK_BLANK_on_BLACK_SQUARE_1=85
INDEX_BLACK_BLANK_on_BLACK_SQUARE_2=86
INDEX_BLACK_BLANK_on_BLACK_SQUARE_3=87
INDEX_BLACK_PAWN_on_BLACK_SQUARE_0=88
INDEX_BLACK_PAWN_on_BLACK_SQUARE_1=89
INDEX_BLACK_PAWN_on_BLACK_SQUARE_2=90
INDEX_BLACK_PAWN_on_BLACK_SQUARE_3=91
INDEX_BLACK_KNIGHT_on_BLACK_SQUARE_0=92
INDEX_BLACK_KNIGHT_on_BLACK_SQUARE_1=93
INDEX_BLACK_KNIGHT_on_BLACK_SQUARE_2=94
INDEX_BLACK_KNIGHT_on_BLACK_SQUARE_3=95
INDEX_BLACK_BISHOP_on_BLACK_SQUARE_0=96
INDEX_BLACK_BISHOP_on_BLACK_SQUARE_1=97
INDEX_BLACK_BISHOP_on_BLACK_SQUARE_2=98
INDEX_BLACK_BISHOP_on_BLACK_SQUARE_3=99
INDEX_BLACK_ROOK_on_BLACK_SQUARE_0=100
INDEX_BLACK_ROOK_on_BLACK_SQUARE_1=101
INDEX_BLACK_ROOK_on_BLACK_SQUARE_2=102
INDEX_BLACK_ROOK_on_BLACK_SQUARE_3=103
INDEX_BLACK_QUEEN_on_BLACK_SQUARE_0=104
INDEX_BLACK_QUEEN_on_BLACK_SQUARE_1=105
INDEX_BLACK_QUEEN_on_BLACK_SQUARE_2=106
INDEX_BLACK_QUEEN_on_BLACK_SQUARE_3=107
INDEX_BLACK_KING_on_BLACK_SQUARE_0=108
INDEX_BLACK_KING_on_BLACK_SQUARE_1=109
INDEX_BLACK_KING_on_BLACK_SQUARE_2=110
INDEX_BLACK_KING_on_BLACK_SQUARE_3=111
